server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    username: root
    password: ibe
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect


  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: OrderConfirmation:com.ibe.order.kafka.OrderConfirmation

#faire appelle au microservice
application:
  config:
    customer-url: http://localhost:8082/api/v1/customer
    product-url: http://localhost:8083/api/v1/product
    payment-url: http://localhost:8085/api/v1/payment